
# Paste in a valid geocoding api key
Googlemaps Key: "<INSERT KEY>"

# Set the document and layer's title here
Title: "Shelters"

# Determine the used columns here
Information:

  # Defines a column storing the place's name
  # Any column with a name containing the words "shelter", "title", "name" or "place" will be used
  name:
    - "Shelter"
    - "Title"
    - "Name"

  # You can define as many columns as necessary
  # This one stores the type of shelter
  type:
    - "Type"
    - "From"

  organizer:
    - "Organizer"
    - "Ran by"
    - "Host"

  address:
    - "Address"

  location:
    - "Address"
    - "Location"
    - "Coordinate"

  website:
    - "url"
    - "link"
    - "website"

  size:
    - "Size"
    - "Capacity"
    - "Occupancy"

# Defines names of special columns
# These columns will be used to determine the type of the place
# and can scale based on a place's maximum capacity
# All columns here are optional except title and location
Special Columns:
  # This column contains a place's title
  title: "name"

  # This column contains a place's location
  # It can be either coordinates or a textual address
  # Addresses are geocoded using Google Maps
  location: "location"
  
  # This column must contain a number for
  # proper scaling
  scaling: "size"

  # This category contains a string which is
  # matched against the defined categories
  categorizer: "type"

# Determines the description for each place
#
# Use {____} to insert the value of a column
# defined above in the information section
# Special placeholders include {category}, which is
# the category of the place
#
# HTML is valid here
Description:
  "
  {name} - {category}
  {type}
  {address}
  Maximum Occupancy: {size} people
  Hosted by {organizer}
  "

# Determines the category for each place
# This helps to group places together with a similar
# style
Categories:

  # The default style
  # Will be used if no other category is specified for the given place
  #
  # All categories build off this one, so changing
  # a value here will affect all categories that don't override it
  "*":
    - color: "#000000"
    - icon: "http://maps.google.com/mapfiles/ms/icons/red-dot.png"
    - identifiers:
      - "unknown"
    - scale: 0.7
    - label_scale: 0.7
  
  # Defines a category called "storm"
  # All places containing the word "weather",
  # "storm", or "hurricane" in the categorizer column
  # will be assigned this category and
  # all style attributes will be applied
  storm:
    - color: "#000000"
    - icon: "https://drive.google.com/uc?id=1XF2EbWOqPECjbDHvAmJT_Ds7LYuUAj1E"
    - identifiers:
      - "weather"
      - "storm"
      - "hurricane"
  
  # Note that there is no color style here,
  # This means that the color of the category
  # is determined by the "*" category
  heat:
    - icon: "https://drive.google.com/uc?id=1LvEhkbw3JUSPTadqPkeGe1Vt4kgoY5XR"
    - identifiers:
      - "hot"
      - "heat"
      - "temperature"
  
  cold:
    - icon: "https://drive.google.com/uc?id=1Wi1WThTK38ozf6aXI0ZuVYgOsIVmibU8"
    - identifiers:
      - "cold"
      - "freezing"
      - "blizzard"
      - "snow"
      - "ice"
  
  # Creates a column called "Hot & Cold"
  # Will match all columns that match both "hot" and "cold"
  # Note that identifiers are ignored in these merged columns
  hot&cold:
    - icon: "https://drive.google.com/uc?id=1mlRhUJB9eNnynlvPNwj1DGQm-Y5InXsn"

  smoke:
    - icon: "https://drive.google.com/uc?id=1K8C-2QtoDWqEm_A6KcfkdAVgpwAa5V_k"
    - identifiers:
      - "smoke"
      - "smog"
      - "fog"
      - "haze"
      - "wildfire"
      - "fire"
      - "air"
      - "pollution"
      - "dust"
  
  overnight:
    - icon: "https://drive.google.com/uc?id=1JbW8uTIHIflhpk2tWIcPYb4po-l-5XVZ"
    - identifiers:
        - "overnight"
        - "night"
        - "nighttime"
        - "home"
        - "sleep"
        - "bed"